---
# tasks file for agent

- name: install k3s on agent
  shell: 
    cmd: INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://"{{K3S_URL}}" K3S_TOKEN="{{K3S_TOKEN}}" ./install.sh
    chdir: /usr/local/usr/