---
# tasks file for install
- name: install k3s
  command: 
    cmd: ./install.sh
    environment:
      INSTALL_K3S_SKIP_DOWNLOAD: "true"
    chdir: roles/install/files/

- name: get master url
  shell: cat /etc/systemd/system/k3s-agent.service.env | awk -F "K3S_URL=" '{printf $2}'
  register: KS3_URL

- name: get master token
  shell: cat /etc/systemd/system/k3s-agent.service.env | awk -F "K3S_TOKEN=" '{printf $2}'
  register: KS3_TOKEN
